import type { BatonPacket } from '@baton/schema';

export function renderPacketMarkdown(packet: BatonPacket): string {
  const lines: string[] = [];
  lines.push(`# ${packet.title}`, '');
  lines.push(
    `**ID:** \`${packet.id}\`  ` +
      `**Status:** ${packet.status}  ` +
      `**Validation:** ${packet.validation_level}  ` +
      `**Task type:** ${packet.task_type}`,
    '',
  );
  lines.push('## Objective', packet.objective, '');
  lines.push('## Current state', packet.current_state, '');
  lines.push('## Next action', packet.next_action, '');

  if (packet.open_questions.length > 0) {
    lines.push('## Open questions');
    for (const q of packet.open_questions) {
      const flag = q.blocking ? ' (blocking)' : '';
      lines.push(`- [${q.status}]${flag} ${q.text}`);
    }
    lines.push('');
  }

  if (packet.acceptance_criteria.length > 0) {
    lines.push('## Acceptance criteria');
    for (const c of packet.acceptance_criteria) {
      const box = c.status === 'met' ? '[x]' : '[ ]';
      const req = c.required ? '' : ' _(optional)_';
      lines.push(`- ${box} ${c.text}${req}`);
    }
    lines.push('');
  }

  if (packet.warnings.length > 0) {
    lines.push('## Warnings');
    for (const w of packet.warnings) {
      const block = w.blocking ? ' (blocking)' : '';
      lines.push(`- **${w.code}** [${w.severity}]${block} — ${w.message}`);
    }
    lines.push('');
  }

  lines.push(
    '---',
    `_Generated by @baton/store. Canonical source: \`packet.json\`. Confidence: ${packet.confidence_score}._`,
    '',
  );
  return lines.join('\n');
}
