/**
 * Shared "call LLM, cache, retry once on parse failure" runner.
 *
 * Per tech spec §7.3 every extractor follows the same dance:
 *   1. Derive a stable cache key from the (system+user) prompt.
 *   2. Probe the cache; on hit, parse + return without a live call.
 *   3. On miss, call `llm.complete({ responseFormat: 'json' })`.
 *   4. Try to parse the JSON. On parse failure, retry ONCE.
 *   5. On second parse failure, return `{ value: null, warning }` so
 *      the pipeline can keep going and surface the failure on the packet.
 *
 * Live-call results are written to the cache on success only; we never
 * cache a parse-failed completion (replaying the same garbage forever
 * would be worse than re-attempting next run).
 */

import { type LLMCache, type LLMProvider, cacheKey as deriveCacheKey } from '@batonai/llm';
import type { CompileWarning } from '../types.js';
import type { ExtractResult } from './types.js';

export interface RunPromptInput {
  system: string;
  user: string;
  /** Used in warning messages and the cache key namespace. */
  extractorName: string;
}

export interface RunPromptDeps {
  llm: LLMProvider;
  cache: LLMCache | null;
  signal?: AbortSignal | undefined;
}

export interface RunPromptResult<T> extends ExtractResult<T> {}

/**
 * The shape we hand back to per-extractor parse functions. Wrapping it
 * lets the parser surface a precise error message without needing to
 * know about caching or token accounting.
 */
export type ParseFn<T> = (raw: string) => T;

/** Shape preserved by every extractor for cleaner per-call wiring. */
export interface RunOptions<T> {
  prompt: RunPromptInput;
  parse: ParseFn<T>;
  warningCode: string;
  /** Optional: limit response size; defaults to provider default. */
  maxTokens?: number;
}

function makeWarning(
  code: string,
  message: string,
  data?: Record<string, unknown>,
): CompileWarning {
  return data === undefined
    ? { code, message, severity: 'warning' }
    : { code, message, severity: 'warning', data };
}

/**
 * Strip common JSON wrapping (markdown code fences, leading/trailing
 * prose) before parsing. Defensive — the prompt explicitly forbids
 * fences, but live models sometimes include them anyway.
 */
function unwrapJson(raw: string): string {
  let s = raw.trim();
  // ```json ... ```  or  ``` ... ```
  if (s.startsWith('```')) {
    const firstNL = s.indexOf('\n');
    if (firstNL !== -1) s = s.slice(firstNL + 1);
    if (s.endsWith('```')) s = s.slice(0, -3);
    s = s.trim();
  }
  // Pull the first balanced `{...}` block if there's leading prose.
  if (!s.startsWith('{')) {
    const open = s.indexOf('{');
    const close = s.lastIndexOf('}');
    if (open !== -1 && close > open) {
      s = s.slice(open, close + 1);
    }
  }
  return s;
}

export function tryParse<T>(
  raw: string,
  parse: ParseFn<T>,
): { ok: true; value: T } | { ok: false; reason: string } {
  try {
    const stripped = unwrapJson(raw);
    const json = JSON.parse(stripped) as unknown;
    return { ok: true, value: parse(JSON.stringify(json)) };
  } catch (err) {
    return { ok: false, reason: err instanceof Error ? err.message : String(err) };
  }
}

/**
 * Drive one extractor end-to-end. The two-call retry on parse failure
 * is implemented here so each extractor is just (prompt, parser).
 */
export async function runPrompt<T>(
  opts: RunOptions<T>,
  deps: RunPromptDeps,
): Promise<ExtractResult<T>> {
  const { llm, cache, signal } = deps;
  const { prompt, parse, warningCode, maxTokens } = opts;

  // Stable provider+model identifiers for cache key + telemetry.
  // Provider exposes its name; model is read from a fresh complete()
  // result lazily, but for the cache key we let the cache derive its
  // own model identifier — we pass model='' to the keyer and rely on
  // the LLMCache::cacheKey contract that both calls produce the same
  // hash given the same system+user+temperature.
  // Note: tests pin the mock provider's model so cache keys collide
  // across test invocations within the same run.
  const provider = llm.name;

  const tryCache = async (): Promise<ExtractResult<T> | null> => {
    if (!cache) return null;
    // We don't know the model up-front; the provider includes it in
    // the result, so derive a stable key from prompt+provider only.
    // This biases towards more cache hits (different models reuse the
    // same cache) — acceptable because the cache value records the
    // model it was generated by.
    const key = deriveCacheKey({
      provider,
      model: '__extractor__',
      systemPrompt: prompt.system,
      userPrompt: prompt.user,
      temperature: 0,
    });
    const hit = await cache.get(key);
    if (!hit) return null;
    const parsed = tryParse(hit.text, parse);
    if (!parsed.ok) {
      // Cached value no longer parses (e.g., schema drift). Drop the
      // cache entry by ignoring it; a fresh live call will overwrite
      // on success below.
      return null;
    }
    return {
      value: parsed.value,
      tokensIn: 0,
      tokensOut: 0,
      callLive: false,
      provider: hit.provider,
      model: hit.model,
    };
  };

  const cached = await tryCache();
  if (cached) return cached;

  // Live call (with retry-once on parse failure).
  let lastReason = '';
  let totalIn = 0;
  let totalOut = 0;
  let lastModel = '';
  for (let attempt = 0; attempt < 2; attempt++) {
    if (signal?.aborted) {
      throw new DOMException('Extract aborted', 'AbortError');
    }
    const completeOpts: Parameters<LLMProvider['complete']>[0] = {
      systemPrompt: prompt.system,
      userPrompt: prompt.user,
      responseFormat: 'json',
      temperature: 0,
    };
    if (signal !== undefined) completeOpts.signal = signal;
    if (maxTokens !== undefined) completeOpts.maxTokens = maxTokens;
    const result = await llm.complete(completeOpts);
    totalIn += result.tokensIn;
    totalOut += result.tokensOut;
    lastModel = result.model;
    const parsed = tryParse(result.text, parse);
    if (parsed.ok) {
      // Cache the underlying completion so a future run can short-circuit.
      if (cache) {
        const key = deriveCacheKey({
          provider,
          model: '__extractor__',
          systemPrompt: prompt.system,
          userPrompt: prompt.user,
          temperature: 0,
        });
        await cache.set(key, result);
      }
      return {
        value: parsed.value,
        tokensIn: totalIn,
        tokensOut: totalOut,
        callLive: true,
        provider: result.provider,
        model: result.model,
      };
    }
    lastReason = parsed.reason;
  }

  // Both attempts failed to parse. Surface as a non-fatal warning.
  return {
    value: null,
    warning: makeWarning(
      warningCode,
      `${prompt.extractorName}: LLM response did not parse as valid JSON after one retry (${lastReason}).`,
      { extractor: prompt.extractorName, reason: lastReason },
    ),
    tokensIn: totalIn,
    tokensOut: totalOut,
    callLive: true,
    provider,
    model: lastModel,
  };
}
