/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RepoContext = {
  [k: string]: unknown;
} & {
  attached: boolean;
  root: string | null;
  vcs: 'git' | 'none';
  branch: string | null;
  base_branch: string | null;
  commit: string | null;
  base_commit: string | null;
  dirty: boolean;
};
export type RefPath = string;
export type Severity = 'info' | 'warning' | 'error' | 'critical';
export type ArtifactType =
  | 'transcript'
  | 'issue'
  | 'diff'
  | 'log'
  | 'note'
  | 'image'
  | 'test-report';

/**
 * Canonical machine-readable task-state artifact for Baton.
 */
export interface BatonPacket {
  schema_version: 'baton.packet/v1';
  id: string;
  title: string;
  status:
    | 'draft'
    | 'ready_for_export'
    | 'awaiting_approval'
    | 'dispatched'
    | 'awaiting_outcome'
    | 'needs_clarification'
    | 'completed'
    | 'abandoned';
  validation_level: 'draft' | 'valid' | 'verified' | 'ready';
  task_type: 'implementation' | 'debugging' | 'review' | 'docs' | 'analysis' | 'generic';
  objective: string;
  current_state: string;
  next_action: string;
  open_questions: OpenQuestion[];
  confidence_score: number;
  repo_context: RepoContext;
  context_items: ContextItem[];
  constraints: Constraint[];
  attempts: Attempt[];
  acceptance_criteria: AcceptanceCriterion[];
  warnings: Warning[];
  provenance_links: ProvenanceLink[];
  source_artifacts: SourceArtifact[];
  policy?: Policy;
  render_hints?: RenderHints;
  /**
   * Reserved extension surface for non-normative metadata.
   */
  extensions?: {
    [k: string]: unknown;
  };
  created_at: string;
  updated_at: string;
}
export interface OpenQuestion {
  id: string;
  text: string;
  blocking: boolean;
  status: 'open' | 'answered' | 'waived';
}
export interface ContextItem {
  kind: 'file' | 'directory' | 'command' | 'doc' | 'test' | 'symbol' | 'diff' | 'log' | 'issue';
  ref: RefPath;
  reason: string;
  priority: number;
  freshness_score: number;
  exists?: boolean | null;
  provenance_refs: string[];
}
export interface Constraint {
  id: string;
  type: 'product' | 'technical' | 'policy' | 'deadline' | 'style' | 'safety';
  text: string;
  severity: Severity;
  source: 'user' | 'repo' | 'ticket' | 'tool' | 'policy';
  /**
   * @minItems 1
   */
  provenance_refs: [string, ...string[]];
}
export interface Attempt {
  id: string;
  tool: string;
  summary: string;
  result: 'succeeded' | 'failed' | 'partial' | 'blocked' | 'abandoned' | 'unknown';
  failure_reason: string | null;
  artifact_refs: string[];
  created_at: string;
}
export interface AcceptanceCriterion {
  id: string;
  text: string;
  status: 'unmet' | 'met' | 'unknown';
  required: boolean;
  source: 'user' | 'ticket' | 'derived';
  provenance_refs: string[];
}
export interface Warning {
  code: string;
  severity: Severity;
  message: string;
  blocking: boolean;
  source: 'schema' | 'lint' | 'policy' | 'repo' | 'adapter';
}
export interface ProvenanceLink {
  id: string;
  field_name: string;
  artifact_id: string;
  source_type: ArtifactType;
  ref: RefPath;
  span_start?: number | null;
  span_end?: number | null;
  excerpt?: string | null;
}
export interface SourceArtifact {
  id: string;
  type: ArtifactType;
  source_tool: string;
  uri: RefPath;
  digest: string;
  created_at: string;
}
export interface Policy {
  approval_required: boolean;
  dispatch_allowed: boolean;
  stale_context: boolean;
  reasons: string[];
}
export interface RenderHints {
  default_target?: 'claude-code' | 'codex' | 'cursor' | 'generic';
  context_budget?: number;
  include_provenance?: boolean;
}
